import Foundation
import UserNotifications

/// Removes the two local-delivery preferences used before Cloudflare webhooks
/// became Dash's only Watchtower notification source.
enum LegacyWatchtowerNotificationSettings {
  static let optInKey = "dash.watchtower_notifications"
  static let baselinesKey = "dash.watchtower_notification_baselines"

  static func clear(defaults: UserDefaults = .standard) {
    defaults.removeObject(forKey: optInKey)
    defaults.removeObject(forKey: baselinesKey)
  }
}

/// Shared iOS authorization for remote Cloudflare alerts, plus removal of local
/// notifications generated by older Dash releases.
@MainActor
enum DashNotificationSupport {
  // _v2: the _v1 migration matched only `.disabled`, so it burned its one shot
  // on every legacy install without ever asking for `.badge`. Renaming the key
  // gives those installs the retry the fixed check can actually use.
  static let badgeAuthorizationMigrationKey = "dash.notifications.badge_migration_v2"

  /// Older builds emitted Watchtower diffs and automatically scheduled domain
  /// expiry reminders. No current code may create either kind; remove pending
  /// and already-delivered remnants without touching Cloudflare/APNs alerts.
  static func removeLegacyGeneratedNotifications(
    center: UNUserNotificationCenter = .current()
  ) async {
    let pending = await center.pendingNotificationRequests()
    let pendingIDs = pending.map(\.identifier).filter(isLegacyGeneratedNotificationIdentifier)
    if !pendingIDs.isEmpty {
      center.removePendingNotificationRequests(withIdentifiers: pendingIDs)
    }

    let delivered = await center.deliveredNotifications()
    let deliveredIDs = delivered.map(\.request.identifier).filter(
      isLegacyGeneratedNotificationIdentifier)
    if !deliveredIDs.isEmpty {
      center.removeDeliveredNotifications(withIdentifiers: deliveredIDs)
    }
  }

  nonisolated static func isLegacyGeneratedNotificationIdentifier(_ identifier: String) -> Bool {
    identifier.hasPrefix("dash.expiry.")
      || identifier == "watchtower.alerts"
      || identifier.hasPrefix("watchtower.alert.")
  }

  /// Requests notification delivery.
  ///
  /// Provisional by default. iOS grants provisional authorization with no
  /// dialog and delivers quietly to Notification Center, then asks the user to
  /// keep or turn off notifications *on the first real alert* — when they can
  /// see what they are deciding about, instead of at the instant they flipped a
  /// switch and have nothing to judge. `.alert` and `.sound` ride along so the
  /// grant is already complete if they choose to keep them prominently.
  ///
  /// Pass `prominently: true` only for an explicit "turn on banners" action:
  /// that is the one case where the system prompt is what the user asked for.
  static func requestAuthorization(prominently: Bool = false) async -> Bool {
    let center = UNUserNotificationCenter.current()
    let options = authorizationOptions(prominently: prominently)
    return (try? await center.requestAuthorization(options: options)) ?? false
  }

  nonisolated static func authorizationOptions(
    prominently: Bool
  ) -> UNAuthorizationOptions {
    prominently ? [.alert, .sound, .badge] : [.alert, .sound, .badge, .provisional]
  }

  /// Older Dash versions asked for alerts and sounds without asking for badge
  /// delivery. Retry that missing option once for an already-authorized user;
  /// iOS remains authoritative when the user has since changed notification
  /// settings, and the migration never nags on every launch.
  static func migrateLegacyBadgeAuthorizationIfNeeded(
    defaults: UserDefaults = .standard
  ) async {
    guard !defaults.bool(forKey: badgeAuthorizationMigrationKey) else { return }
    let center = UNUserNotificationCenter.current()
    let settings = await center.notificationSettings()
    guard
      let options = badgeAuthorizationMigrationOptions(
        authorizationStatus: settings.authorizationStatus,
        badgeSetting: settings.badgeSetting)
    else {
      defaults.set(true, forKey: badgeAuthorizationMigrationKey)
      return
    }
    _ = try? await center.requestAuthorization(options: options)
    defaults.set(true, forKey: badgeAuthorizationMigrationKey)
  }

  /// Preserve quiet authorization while adding the previously omitted badge
  /// option. Only an explicit "turn on banners" action may make a prominent
  /// request.
  ///
  /// The interesting value is `.notSupported`, not `.disabled`: iOS reports a
  /// setting that was *never requested* as `.notSupported`, and reserves
  /// `.disabled` for one the user switched off in Settings afterwards. Every
  /// install that predates the badge option therefore reports `.notSupported`,
  /// so matching only `.disabled` skipped exactly the population the migration
  /// exists for — and with it `setBadgeCount`, which needs the same grant.
  nonisolated static func badgeAuthorizationMigrationOptions(
    authorizationStatus: UNAuthorizationStatus,
    badgeSetting: UNNotificationSetting
  ) -> UNAuthorizationOptions? {
    guard badgeSetting != .enabled else { return nil }
    switch authorizationStatus {
    case .authorized:
      return [.badge]
    case .provisional:
      return [.badge, .provisional]
    case .notDetermined, .denied, .ephemeral:
      return nil
    @unknown default:
      return nil
    }
  }

  /// True while Dash is delivering quietly and could be promoted to banners.
  static func isProvisional() async -> Bool {
    await UNUserNotificationCenter.current().notificationSettings().authorizationStatus
      == .provisional
  }
}
