/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
	presets: [require('nativewind/preset')],
	darkMode: 'media',
	theme: {
		extend: {
			borderRadius: {
				kumo: '20px',
			},
			colors: {
				accent: 'rgb(var(--color-accent) / <alpha-value>)',
				base: 'rgb(var(--color-base) / <alpha-value>)',
				badge: {
					blue: 'rgb(var(--color-badge-blue) / <alpha-value>)',
					green: 'rgb(var(--color-badge-green) / <alpha-value>)',
					inverted: 'rgb(var(--color-badge-inverted) / <alpha-value>)',
					'inverted-fg': 'rgb(var(--color-badge-inverted-fg) / <alpha-value>)',
					neutral: 'rgb(var(--color-badge-neutral) / <alpha-value>)',
					orange: 'rgb(var(--color-badge-orange) / <alpha-value>)',
					purple: 'rgb(var(--color-badge-purple) / <alpha-value>)',
					red: 'rgb(var(--color-badge-red) / <alpha-value>)',
					teal: 'rgb(var(--color-badge-teal) / <alpha-value>)',
					'teal-subtle': 'rgb(var(--color-badge-teal-subtle) / <alpha-value>)',
					'teal-subtle-fg': 'rgb(var(--color-badge-teal-subtle-fg) / <alpha-value>)',
				},
				brand: 'rgb(var(--color-brand) / <alpha-value>)',
				canvas: 'rgb(var(--color-canvas) / <alpha-value>)',
				control: 'rgb(var(--color-control) / <alpha-value>)',
				danger: {
					DEFAULT: 'rgb(var(--color-danger) / <alpha-value>)',
					tint: 'rgb(var(--color-danger-tint) / <alpha-value>)',
				},
				default: 'rgb(var(--color-default) / <alpha-value>)',
				elevated: 'rgb(var(--color-elevated) / <alpha-value>)',
				fill: 'rgb(var(--color-fill) / <alpha-value>)',
				focus: 'rgb(var(--color-focus) / <alpha-value>)',
				hairline: 'rgb(var(--color-hairline) / <alpha-value>)',
				info: {
					DEFAULT: 'rgb(var(--color-info) / <alpha-value>)',
					tint: 'rgb(var(--color-info-tint) / <alpha-value>)',
				},
				inverse: 'rgb(var(--color-inverse) / <alpha-value>)',
				line: 'rgb(var(--color-line) / <alpha-value>)',
				placeholder: 'rgb(var(--color-placeholder) / <alpha-value>)',
				recessed: 'rgb(var(--color-recessed) / <alpha-value>)',
				strong: 'rgb(var(--color-strong) / <alpha-value>)',
				subtle: 'rgb(var(--color-subtle) / <alpha-value>)',
				switch: {
					'track-off': 'rgb(var(--color-switch-track-off) / <alpha-value>)',
					'track-off-ring': 'rgb(var(--color-switch-track-off-ring) / <alpha-value>)',
					'track-on': 'rgb(var(--color-switch-track-on) / <alpha-value>)',
					'track-on-ring': 'rgb(var(--color-switch-track-on-ring) / <alpha-value>)',
				},
				success: {
					DEFAULT: 'rgb(var(--color-success) / <alpha-value>)',
					tint: 'rgb(var(--color-success-tint) / <alpha-value>)',
				},
				tint: 'rgb(var(--color-tint) / <alpha-value>)',
				warning: {
					DEFAULT: 'rgb(var(--color-warning) / <alpha-value>)',
					tint: 'rgb(var(--color-warning-tint) / <alpha-value>)',
				},
			},
			fontSize: {
				xs: ['12px', { lineHeight: '16px' }],
				sm: ['13px', { lineHeight: '18px' }],
				base: ['14px', { lineHeight: '20px' }],
				lg: ['16px', { lineHeight: '24px' }],
				xl: ['20px', { lineHeight: '26px' }],
				'2xl': ['22px', { lineHeight: '28px' }],
			},
		},
	},
}
